import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Homee from './Homee';
import About from './About';
import Contact from './Contact';
import Link from 'next/link';
import myimg from  '../public/img/cs50.PNG';
import logo from '../public/img/logo-net.png';
import tv from '../public/img/tv.png';
import girl from '../public/img/mobile-0819.jpg';
import kids from '../public/img/kids.png'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel='stylesheet' type="text/css" href='https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.4/css/fontawesome.min.css'/>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.first}>
      <nav className={styles.navbar}>
                    <div className={styles.logo}>
                        <Image width={160} height={60} src={logo}/>
                    </div>
                    <div className={styles.btns}>
                        <select>
                            <option>English</option>
                            <option>Arabic</option>
                            <option>Frensh</option>
                            <option>Deutsh</option>
                        </select>
                        <button>Sign in</button>
                    </div>
                </nav>
                <div className={styles.articles}>
                  <h1>Unlimited movies, TV <br /> shows, and more.</h1>
                  <h4>Watch anywhere. Cancel anytime.</h4>
                  <p>Ready to watch? Enter your email to create or restart your membership.</p>
                  <input type="text" placeholder='Email Adress'/>
                  <button>Get Started &nbsp; > </button>
                </div>
                </div>
                
      <main>
        <div className={styles.tv}>
          <div className={styles.tvparent}>
            <div className={styles.tvbox1}>
              <h1>Enjoy on your TV.</h1>
              <h2>Watch on Smart TVs, Playstation, Xbox, <br /> Chromecast, Apple TV, Blu-ray players, and <br /> more.</h2>
            </div>
            <div className={styles.tvbox2}>
              <Image width={380} height={340}  src={tv} alt="tv" />
            </div>
          </div>

          <div className={styles.tvparent1}>
          <div className={styles.box1}>
        <Image width={380} height={340} src={girl} alt="mobile"/>
          </div>
          <div className={styles.box2}>
            <h1>Download your shows <br /> to watch offline.</h1>
            <h2>Save your favorites easily and always have something to watch.</h2>
          </div>
        </div>

        <div className={styles.tvparent1}>
          <div className={styles.box1}>
        <Image width={380} height={340} src={kids} alt="mobile"/>
          </div>
          <div className={styles.box2}>
            <h1>Create profiles for kids.</h1>
            <h2>Send kids on adventures with their favorite <br /> characters in a space made just for them— <br />free with your membership..</h2>
          </div>
        </div>
        <div className={styles.faqs}>
          <h1>Frequently Asked Questions</h1>

       <small>Ready to watch? Enter your email to create or restart your membership.</small> <br />
       <input type="text" placeholder='Email Adress'/>
                  <button>Get Started &nbsp; > </button>
          </div>
       <div className={styles.footer}>
         <div className={styles.farent}>
           <ul>
             <li className={styles.li}>FAQ</li>
             <li className={styles.li}>Investor Relations</li>
             <li className={styles.li}>Privacy</li>
             <li className={styles.li}>Speed Test</li>
             <li className={styles.li}> <select>
                            <option>English</option>
                            <option>Arabic</option>
                            <option>Frensh</option>
                            <option>Deutsh</option>
                        </select></li>
                        <li className={styles.li}><pre>Netflix Morocco</pre></li>
           </ul>
           <ul>
             <li className={styles.li} >Help Center</li>
             <li className={styles.li} >Jobs</li>
             <li className={styles.li} >Cookie Preferences</li>
             <li className={styles.li} >Legal Notices</li>
             
           </ul>

           <ul>
             <li className={styles.li} >Account</li>
             <li className={styles.li} >Ways to Watch</li>
             <li className={styles.li} >Corporate Information</li>
             <li className={styles.li} >Only on Netflix</li>
           </ul>

           <ul>
             <li className={styles.li}>Media Center</li>
             <li className={styles.li}>Terms of Use</li>
             <li className={styles.li}>Contact Us</li>
           </ul>
         </div>
       </div>
        </div>
      </main>
    </div>
  )
}
